test

diff --git a/.github/workflows/mt-sync-code-data.yml b/.github/workflows/mt-sync-code-data.yml
--- a/.github/workflows/mt-sync-code-data.yml
+++ b/.github/workflows/mt-sync-code-data.yml
@@ -149,6 +149,7 @@ jobs:
 
       - name: MT check if image generation required
         id: mt-check-image-gen-required
+        continue-on-error: true
         if: ${{ env.MT_IS_AGENCY_BIKE != 'true' && env.MT_IS_MAIN_REPO != 'true' }}
         run: |
           # check if app-android/src/main/res/values/gtfs_rts_values_gen.xml changed (gtfs_rts_color | gtfs_rts_agency_type)
@@ -156,11 +157,11 @@ jobs:
           # git diff-index --name-only --quiet HEAD -- app-android/src/main/res/values/gtfs_rts_values_gen.xml
           RESULT=$(git diff-index --name-only HEAD -- "app-android/src/main/res/values/gtfs_rts_values_gen.xml" | wc -l)
           if [ "$RESULT" -gt 0 ]; then
-            echo "Changes detected in gtfs_rts_values_gen.xml. Image generation is required.";
+            exit 0 # success
           else
-            echo "No changes detected in gtfs_rts_values_gen.xml. Image generation is not required.";
+            exit 1 # fail
           fi
-          echo "image_gen_required=$RESULT" >> "$GITHUB_OUTPUT"
+          # echo "image_gen_required=$RESULT" >> "$GITHUB_OUTPUT"
 
       - name: MT push commits
         if: ${{ env.MT_IS_AGENCY_BIKE != 'true' && env.MT_IS_MAIN_REPO != 'true' }}
@@ -191,14 +192,14 @@ jobs:
       # ----------
 
       - name: MT generate images if required
-        if: ${{ env.MT_IS_AGENCY_BIKE != 'true' && env.MT_IS_MAIN_REPO != 'true' && steps.mt-check-image-gen-required.outputs.image_gen_required > '0' }}
+        if: ${{ env.MT_IS_AGENCY_BIKE != 'true' && env.MT_IS_MAIN_REPO != 'true' && steps.mt-check-image-gen-required.outputs.outcome == 'success' }}
         run: |
           ./commons/code_setup.sh;
         env:
           MT_GENERATE_IMAGES: true
 
       - name: MT commit image change
-        if: ${{ env.MT_IS_AGENCY_BIKE != 'true' && env.MT_IS_MAIN_REPO != 'true' && steps.mt-check-image-gen-required.outputs.image_gen_required > '0' }}
+        if: ${{ env.MT_IS_AGENCY_BIKE != 'true' && env.MT_IS_MAIN_REPO != 'true' && steps.mt-check-image-gen-required.outputs.outcome == 'success' }}
         run: |
           git add -v -A -- ':(glob)**/*.png'
           if git diff --staged --quiet; then
